language: node_js
node_js:
    - "0.11"
    - "0.10"

env:
    - NO_ETCD=true

before_install:
    - sudo apt-get update
    - npm install -g gulp
    - sudo apt-get install redis-server memcached

after_install:
    # Pythonic tests require these to be started manually
    - sudo apt-get install python-pip
    - redis-server &
    - ./bin/hipache -c config/config_test.json &

before_script:
    # Hinting - XXX should fail!
    - npm run-script hint

after_script:
    # Running pythonic functional tests
    - (cd test/functional && sudo pip install -r requirements.txt)
    - (cd test/functional && python -m unittest discover)
    # Coveralls report
    - npm run coveralls
