language: node_js
node_js:
  - "0.10"
  - "0.8"

script:
    - npm test
    - npm run-script jshint
    # Running functional tests
    - sudo apt-get update
    - sudo apt-get install python-pip redis-server
    - ./bin/hipache -c config/config_test.json &
    - redis-server &
    - cd test/functional && sudo pip install -r requirements.txt
    - cd test/functional && python -m unittest discover
